#!/bin/bash

# HostelMate Deployment Helper Script
echo "=========================================="
echo "🚀 HostelMate Deployment Guide"
echo "=========================================="
echo ""
echo "📋 Steps to Deploy:"
echo ""
echo "1. Database Setup (Neon - PostgreSQL):"
echo "   - Go to https://neon.tech"
echo "   - Create a project and copy the connection string"
echo ""
echo "2. Backend Deployment (Render):"
echo "   - Go to https://render.com"
echo "   - New Web Service → Connect GitHub repo"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Add Env Vars (DATABASE_URL, JWT_SECRET, etc.)"
echo ""
echo "3. Frontend Deployment (Vercel):"
echo "   - Go to https://vercel.com"
echo "   - Import Project → Connect GitHub repo"
echo "   - Root Directory: frontend"
echo "   - Add Env Var: REACT_APP_API_URL=https://your-backend.onrender.com/api"
echo ""
echo "4. Run Migrations (Render Shell):"
echo "   - Go to Render → Backend Service → Shell"
echo "   - Run: npm run prisma:generate && npm run migrate && npm run prisma:seed"
echo ""
echo "✅ Done!"
